server.port=8081
apisports.key=171dc277393c16a592e2025bf8270607
eventhub.connection-string=Endpoint=sb://sportscore-eventhub.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=3W8p+1GwzI8QNlBvuA6jsJVkS7WcR6rH1+AEhEfWU8A=
eventhub.name=sportscore-eventhub-1