export interface LapRecord {
  time: string;
  driver: string;
  year: number;
}

export interface CircuitDetails {
  slug: string;
  name: string;
  country: string;
  city: string;
  flagEmoji: string;
  lengthKm: string;
  laps: number;
  raceDistanceKm: string;
  firstGrandPrix: number;
  lapRecord: LapRecord;
  mapImage: string;
  description: string;
}

export const CIRCUITS: Record<string, CircuitDetails> = {
  australia: {
    slug: "australia",
    name: "Albert Park Circuit",
    country: "Australia",
    city: "Melbourne",
    flagEmoji: "🇦🇺",
    lengthKm: "5.278 km",
    laps: 58,
    raceDistanceKm: "306.124 km",
    firstGrandPrix: 1996,
    lapRecord: { time: "1:19.813", driver: "Charles Leclerc", year: 2024 },
    mapImage: "/f1/circuits-spec/australia.jpeg",
    description: "Set around Albert Park Lake, Melbourne's high-speed street circuit combines rapid directional changes with picturesque parkland surroundings.",
  },
  china: {
    slug: "china",
    name: "Shanghai International Circuit",
    country: "China",
    city: "Shanghai",
    flagEmoji: "🇨🇳",
    lengthKm: "5.451 km",
    laps: 56,
    raceDistanceKm: "305.066 km",
    firstGrandPrix: 2004,
    lapRecord: { time: "1:32.238", driver: "Michael Schumacher", year: 2004 },
    mapImage: "/f1/circuits-spec/china.jpeg",
    description: "Designed to resemble the Chinese character 'Shang' (上), featuring one of the longest back straights in modern motorsport.",
  },
  japan: {
    slug: "japan",
    name: "Suzuka International Racing Course",
    country: "Japan",
    city: "Suzuka",
    flagEmoji: "🇯🇵",
    lengthKm: "5.807 km",
    laps: 53,
    raceDistanceKm: "307.471 km",
    firstGrandPrix: 1987,
    lapRecord: { time: "1:30.983", driver: "Lewis Hamilton", year: 2019 },
    mapImage: "/f1/circuits-spec/japan.jpeg",
    description: "A legendary figure-eight crossover layout revered by drivers for its sweeping 'Esses', 130R corner, and high technical demand.",
  },
  bahrain: {
    slug: "bahrain",
    name: "Bahrain International Circuit",
    country: "Bahrain",
    city: "Sakhir",
    flagEmoji: "🇧🇭",
    lengthKm: "5.412 km",
    laps: 57,
    raceDistanceKm: "308.238 km",
    firstGrandPrix: 2004,
    lapRecord: { time: "1:31.447", driver: "Pedro de la Rosa", year: 2005 },
    mapImage: "/f1/circuits-spec/bahrain.jpeg",
    description: "A night-race spectacle in the desert known for heavy braking zones, multiple overtaking spots, and abrasive asphalt.",
  },
  "saudi-arabia": {
    slug: "saudi-arabia",
    name: "Jeddah Corniche Circuit",
    country: "Saudi Arabia",
    city: "Jeddah",
    flagEmoji: "🇸🇦",
    lengthKm: "6.174 km",
    laps: 50,
    raceDistanceKm: "308.450 km",
    firstGrandPrix: 2021,
    lapRecord: { time: "1:30.734", driver: "Lewis Hamilton", year: 2021 },
    mapImage: "/f1/circuits-spec/saudi-arabia.jpeg",
    description: "The fastest street circuit in Formula 1 history, winding along the Red Sea coast with high-speed blind turns.",
  },
  miami: {
    slug: "miami",
    name: "Miami International Autodrome",
    country: "United States",
    city: "Miami Gardens",
    flagEmoji: "🇺🇸",
    lengthKm: "5.412 km",
    laps: 57,
    raceDistanceKm: "308.326 km",
    firstGrandPrix: 2022,
    lapRecord: { time: "1:29.708", driver: "Max Verstappen", year: 2023 },
    mapImage: "/f1/circuits-spec/miami.jpeg",
    description: "Built around Hard Rock Stadium, featuring a mix of long straights and a tight, elevated chicane complex.",
  },
  imola: {
    slug: "imola",
    name: "Autodromo Enzo e Dino Ferrari",
    country: "Italy",
    city: "Imola",
    flagEmoji: "🇮🇹",
    lengthKm: "4.909 km",
    laps: 63,
    raceDistanceKm: "309.049 km",
    firstGrandPrix: 1980,
    lapRecord: { time: "1:15.484", driver: "Lewis Hamilton", year: 2020 },
    mapImage: "/f1/circuits-spec/imola.jpeg",
    description: "An iconic anti-clockwise classic circuit flowing through Emilia-Romagna, packed with historic corners like Tamburello and Piratella.",
  },
  monaco: {
    slug: "monaco",
    name: "Circuit de Monaco",
    country: "Monaco",
    city: "Monte Carlo",
    flagEmoji: "🇲🇨",
    lengthKm: "3.337 km",
    laps: 78,
    raceDistanceKm: "260.286 km",
    firstGrandPrix: 1950,
    lapRecord: { time: "1:12.909", driver: "Lewis Hamilton", year: 2021 },
    mapImage: "/f1/circuits-spec/monaco.jpeg",
    description: "The jewel in F1's crown: razor-thin margins between armco barriers, the Grand Hotel Hairpin, and the Tunnel.",
  },
  canada: {
    slug: "canada",
    name: "Circuit Gilles Villeneuve",
    country: "Canada",
    city: "Montreal",
    flagEmoji: "🇨🇦",
    lengthKm: "4.361 km",
    laps: 70,
    raceDistanceKm: "305.270 km",
    firstGrandPrix: 1978,
    lapRecord: { time: "1:13.078", driver: "Valtteri Bottas", year: 2019 },
    mapImage: "/f1/circuits-spec/canada.jpeg",
    description: "Located on Notre Dame Island, famous for stop-and-go heavy chicanes and the infamous 'Wall of Champions'.",
  },
  spain: {
    slug: "spain",
    name: "Circuit de Barcelona-Catalunya",
    country: "Spain",
    city: "Montmeló",
    flagEmoji: "🇪🇸",
    lengthKm: "4.657 km",
    laps: 66,
    raceDistanceKm: "307.236 km",
    firstGrandPrix: 1991,
    lapRecord: { time: "1:16.330", driver: "Max Verstappen", year: 2023 },
    mapImage: "/f1/circuits-spec/spain.jpeg",
    description: "The benchmark test track demanding all-round aerodynamic balance through sweeping medium-to-high speed turns.",
  },
  austria: {
    slug: "austria",
    name: "Red Bull Ring",
    country: "Austria",
    city: "Spielberg",
    flagEmoji: "🇦🇹",
    lengthKm: "4.318 km",
    laps: 71,
    raceDistanceKm: "306.452 km",
    firstGrandPrix: 1970,
    lapRecord: { time: "1:05.619", driver: "Carlos Sainz Jr.", year: 2020 },
    mapImage: "/f1/circuits-spec/austria.jpeg",
    description: "A short, fast alpine circuit with dramatic elevation changes and concise heavy-braking overtaking spots.",
  },
  "great-britain": {
    slug: "great-britain",
    name: "Silverstone Circuit",
    country: "United Kingdom",
    city: "Silverstone",
    flagEmoji: "🇬🇧",
    lengthKm: "5.891 km",
    laps: 52,
    raceDistanceKm: "306.198 km",
    firstGrandPrix: 1950,
    lapRecord: { time: "1:27.097", driver: "Max Verstappen", year: 2020 },
    mapImage: "/f1/circuits-spec/great-britain.jpeg",
    description: "The birthplace of Formula 1 World Championship racing, world-famous for high-downforce sequence corners Maggotts, Becketts, and Chapel.",
  },
  belgium: {
    slug: "belgium",
    name: "Circuit de Spa-Francorchamps",
    country: "Belgium",
    city: "Stavelot",
    flagEmoji: "🇧🇪",
    lengthKm: "7.004 km",
    laps: 44,
    raceDistanceKm: "308.052 km",
    firstGrandPrix: 1950,
    lapRecord: { time: "1:46.286", driver: "Valtteri Bottas", year: 2018 },
    mapImage: "/f1/circuits-spec/belgium.jpeg",
    description: "The longest track on the calendar, carving through Ardennes forest features Eau Rouge/Raidillon and unpredictable weather.",
  },
  hungary: {
    slug: "hungary",
    name: "Hungaroring",
    country: "Hungary",
    city: "Mogyoród",
    flagEmoji: "🇭🇺",
    lengthKm: "4.381 km",
    laps: 70,
    raceDistanceKm: "306.630 km",
    firstGrandPrix: 1986,
    lapRecord: { time: "1:16.627", driver: "Lewis Hamilton", year: 2020 },
    mapImage: "/f1/circuits-spec/hungary.jpeg",
    description: "Often called 'Monaco without walls', a twisty, non-stop rhythm track where track position in qualifying is paramount.",
  },
  netherlands: {
    slug: "netherlands",
    name: "Circuit Zandvoort",
    country: "Netherlands",
    city: "Zandvoort",
    flagEmoji: "🇳🇱",
    lengthKm: "4.259 km",
    laps: 72,
    raceDistanceKm: "306.587 km",
    firstGrandPrix: 1952,
    lapRecord: { time: "1:11.097", driver: "Lewis Hamilton", year: 2021 },
    mapImage: "/f1/circuits-spec/netherlands.jpeg",
    description: "An undulating coastal dune roller coaster circuit, highlighted by unique 18-degree steep banked corners.",
  },
  italy: {
    slug: "italy",
    name: "Autodromo Nazionale Monza",
    country: "Italy",
    city: "Monza",
    flagEmoji: "🇮🇹",
    lengthKm: "5.793 km",
    laps: 53,
    raceDistanceKm: "306.720 km",
    firstGrandPrix: 1950,
    lapRecord: { time: "1:21.046", driver: "Rubens Barrichello", year: 2004 },
    mapImage: "/f1/circuits-spec/italy.jpeg",
    description: "The 'Temple of Speed', where low-downforce setups hit top speeds through Curva Grande, Lesmo, and the Parabolica.",
  },
  azerbaijan: {
    slug: "azerbaijan",
    name: "Baku City Circuit",
    country: "Azerbaijan",
    city: "Baku",
    flagEmoji: "🇦🇿",
    lengthKm: "6.003 km",
    laps: 51,
    raceDistanceKm: "306.049 km",
    firstGrandPrix: 2016,
    lapRecord: { time: "1:43.009", driver: "Charles Leclerc", year: 2019 },
    mapImage: "/f1/circuits-spec/azerbaijan.jpeg",
    description: "Contrasts a massive 2.2km flat-out main straight with an ultra-narrow medieval Castle section.",
  },
  singapore: {
    slug: "singapore",
    name: "Marina Bay Street Circuit",
    country: "Singapore",
    city: "Singapore",
    flagEmoji: "🇸🇬",
    lengthKm: "4.940 km",
    laps: 62,
    raceDistanceKm: "306.143 km",
    firstGrandPrix: 2008,
    lapRecord: { time: "1:35.867", driver: "Lewis Hamilton", year: 2023 },
    mapImage: "/f1/circuits-spec/singapore.jpeg",
    description: "The original night race: high humidity, physical driver endurance challenge, and 19 bumps and corners.",
  },
  usa: {
    slug: "usa",
    name: "Circuit of the Americas",
    country: "United States",
    city: "Austin",
    flagEmoji: "🇺🇸",
    lengthKm: "5.513 km",
    laps: 56,
    raceDistanceKm: "308.405 km",
    firstGrandPrix: 2012,
    lapRecord: { time: "1:36.169", driver: "Charles Leclerc", year: 2019 },
    mapImage: "/f1/circuits-spec/usa.jpeg",
    description: "Features a steep uphill climb into Turn 1, taking inspiration from classic European corner designs.",
  },
  mexico: {
    slug: "mexico",
    name: "Autódromo Hermanos Rodríguez",
    country: "Mexico",
    city: "Mexico City",
    flagEmoji: "🇲🇽",
    lengthKm: "4.304 km",
    laps: 71,
    raceDistanceKm: "305.354 km",
    firstGrandPrix: 1963,
    lapRecord: { time: "1:17.774", driver: "Valtteri Bottas", year: 2021 },
    mapImage: "/f1/circuits-spec/mexico.jpeg",
    description: "Situated 2,200 meters above sea level in thin air, concluding with a slow, stadium-like Foro Sol section.",
  },
  brazil: {
    slug: "brazil",
    name: "Autódromo José Carlos Pace",
    country: "Brazil",
    city: "São Paulo",
    flagEmoji: "🇧🇷",
    lengthKm: "4.309 km",
    laps: 71,
    raceDistanceKm: "305.879 km",
    firstGrandPrix: 1973,
    lapRecord: { time: "1:10.540", driver: "Valtteri Bottas", year: 2018 },
    mapImage: "/f1/circuits-spec/brazil.jpeg",
    description: "Interlagos: anti-clockwise undulating track featuring the Senna S and legendary chaotic rain races.",
  },
  "las-vegas": {
    slug: "las-vegas",
    name: "Las Vegas Strip Circuit",
    country: "United States",
    city: "Las Vegas",
    flagEmoji: "🇺🇸",
    lengthKm: "6.201 km",
    laps: 50,
    raceDistanceKm: "309.958 km",
    firstGrandPrix: 2023,
    lapRecord: { time: "1:35.490", driver: "Oscar Piastri", year: 2023 },
    mapImage: "/f1/circuits-spec/las-vegas.jpeg",
    description: "A neon-lit night street race blasting down the world-famous Las Vegas Boulevard at top speeds exceeding 340 km/h.",
  },
  qatar: {
    slug: "qatar",
    name: "Lusail International Circuit",
    country: "Qatar",
    city: "Lusail",
    flagEmoji: "🇶🇦",
    lengthKm: "5.419 km",
    laps: 57,
    raceDistanceKm: "308.611 km",
    firstGrandPrix: 2021,
    lapRecord: { time: "1:24.319", driver: "Max Verstappen", year: 2023 },
    mapImage: "/f1/circuits-spec/qatar.jpeg",
    description: "Fast and flowing Moto-GP origin circuit characterized by medium and high-speed corner sequences.",
  },
  "abu-dhabi": {
    slug: "abu-dhabi",
    name: "Yas Marina Circuit",
    country: "United Arab Emirates",
    city: "Abu Dhabi",
    flagEmoji: "🇦🇪",
    lengthKm: "5.281 km",
    laps: 58,
    raceDistanceKm: "306.183 km",
    firstGrandPrix: 2009,
    lapRecord: { time: "1:26.103", driver: "Max Verstappen", year: 2021 },
    mapImage: "/f1/circuits-spec/abu-dhabi.jpeg",
    description: "The traditional twilight season finale featuring a marina sector, hotel pass-through, and long back straights.",
  },
};

export function getCircuitBySlug(slug: string): CircuitDetails | null {
  const key = slug.toLowerCase().trim();
  return CIRCUITS[key] ?? null;
}

export function getAllCircuits(): CircuitDetails[] {
  return Object.values(CIRCUITS);
}